LoginMVC_Database/Controllers/FakePersonController.cs
using LoginMVC_Database.Data;
using LoginMVC_Database.Interfaces;
using LoginMVC_Database.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LoginMVC_Database.Controllers
{
    public class FakePersonController : Controller
    {

        private readonly ILoginMVCRepository _loginMVCRepository;

        public FakePersonController(ILoginMVCRepository loginMVCRepository)
        {
            _loginMVCRepository = loginMVCRepository;
        }
        public async Task<IActionResult> Data()
        {
            if (User.Identity.IsAuthenticated)//checks if the user is logged in
            {
                try
                {
                    var objPersonDataList = await _loginMVCRepository.GetAllFakePeople();
                    return View(objPersonDataList);
                }
                catch (Exception ex)
                {
                    return View(new List<FakePersonData>());
                }
            }
            else
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(FakePersonData fakePerson)
        {
           /* if (_context.FakePeople.Any(n => n.LastName == obj.LastName && n.FirstName == obj.FirstName && n.Age == obj.Age)) //If First name and Last name and age are the same, give error
            {
                ModelState.AddModelError("name", "Cannot have an existing person added into the database");
            }
            if (obj.LastName.Any(char.IsDigit))
            {
                ModelState.AddModelError("LastName", "Last Name cannot contain numbers");
            }
            if (obj.FirstName.Any(char.IsDigit))
            {
                ModelState.AddModelError("FirstName", "First Name cannot contain numbers");
            }
            */

            if (ModelState.IsValid)//if everything from FakePersonController.cs is validated like maxlenght and display order, then return valid and execute
            {
                _loginMVCRepository.AddFakePerson(fakePerson);//This will add the category object(made by the user input) to the fakeperson table. This keeps track of the changes
                TempData["success"] = "Person created succesfully"; //"success" is the key name
                return RedirectToAction("Data");//This will refresh the database table and show the new stuff
            }
            return View(fakePerson);//stays on the create category page
        }
        public async Task <IActionResult> Edit(int id)//This is a server side check
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var getPersonID = await _loginMVCRepository.GetIdAsync(id); //will work off the primary key off the model

            if (getPersonID == null)
            {
                return NotFound();
            }
            return View(getPersonID);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(FakePersonData fakePerson)//This is post http, meaning what the server receives from the user
        {

            if (ModelState.IsValid)//if everything from FakePersonData.cs is validated like maxlenght and Id, then return valid and execute
            {
                _loginMVCRepository.UpdateFakePerson(fakePerson);//This will Update the category object(made by the user input) to the category table. This keeps track of the changes
                TempData["success"] = "Category updated succesfully";
                return RedirectToAction("Data");//This will refresh the database table and show the new stuff
            }
            return View(fakePerson);//stays on the create category page
        }

        public async Task<IActionResult> Delete(int id)//This is a server side check
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var getPersonID = await _loginMVCRepository.GetIdAsync(id); //will work off the primary key off the model

            if (getPersonID == null)
            {
                return NotFound();
            }
            return View(getPersonID);
        }

        [HttpPost, ActionName("Delete")]//this returns the input from the user side to the back-end and the actionName is "Delete"
        //send data to a server to create/update a resource
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeletePOST(int id)
        {
            var getPersonID = await _loginMVCRepository.GetIdAsync(id);

            if(getPersonID == null)
            {
                return NotFound();
            }
            _loginMVCRepository.DeleteFakePerson(id);
            TempData["success"] = "Category deleted succesfully";
            return RedirectToAction("Data");
        }
    }

}

LoginMVC_Database/Views/FakePerson/Create.cshtml
@model FakePersonData

<form method="post">
    
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Person</h2>
            <hr />
        </div>

        <div asp-validation-summary="All" class="text-danger"></div>  <!--This will display the error in a different text above all of the fields. List all the errors above the fields-->
        
       
        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control"/>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Age" class="p-0"></label>
            <input asp-for="Age" class="form-control" />
        </div>

        <div class="row">
             <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Create</button>
            </div>

            <div class="col-6 col-md-3 mt-2">
                <a asp-controller="FakePerson" asp-action="Data" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

LoginMVC_Database/Views/FakePerson/Data.cshtml
@model List<LoginMVC_Database.Models.FakePersonData>

@{
    ViewData["Title"] = "Fake Person Details";
}

<h3>@ViewData["Title"]</h3>
<hr />

<div>

    @if (User.Identity.IsAuthenticated)
    {
        if(User.IsInRole("Admin")){
        <a asp-controller="FakePerson" asp-action="Create" class="btn btn-primary mb-3">Create Person</a>
        }
      <form> 
        <table class="table table-responsive table-hover">
            <thead>
                <tr class="table-active">
                    <th>
                        ID
                    </th>

                    <th>
                        First Name
                    </th>

                    <th>
                        Last Name
                    </th>

                    <th>
                        Age
                    </th>
                    <th>
                        Action
                    </th>

                </tr>
            </thead>
            <tbody>
                    @if(Model != null && Model.Any())
                    {
                        @foreach (var person in Model)
                        {
                            <tr>
                                <td>
                                    @person.Id
                                </td>
                                <td>
                                    @person.FirstName
                                </td>
                                <td>
                                    @person.LastName
                                </td>
                                <td>
                                    @person.Age
                                </td>
                                <td>
                                    <div class="btn-group brn-group-sm">
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a asp-controller="FakePerson" asp-action="Edit" asp-route-Id="@person.Id" class="btn btn-primary">Edit</a>
                                        }
                                        
                                    </div>

                                    <div class="btn-group brn-group-sm">
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a asp-controller="FakePerson" asp-action="Delete" asp-route-Id="@person.Id" class="btn btn-danger">Delete</a>
                                        }else{
                                            <div class="alert  alert-danger alert-sm my-md-auto small" role="alert">
                                                No action allowed.
                                            </div>
                                        }
                                    </div>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="6">
                                No Person data available
                            </td>
                        </tr>
                    }
                </tbody>
        </table>
      </form>
    }
    else
    {

        <p>No data available.</p>
    }
    

</div>
     

LoginMVC_Database/Views/FakePerson/Delete.cshtml
@model FakePersonData

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" disabled class="form-control" />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Age" class="p-0"></label>
            <input asp-for="Age" disabled class="form-control" />
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="FakePerson" asp-action="Data" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

LoginMVC_Database/Views/FakePerson/Edit.cshtml
@model FakePersonData

<form method="post">
    
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Person</h2>
            <hr />
        </div>

        <div asp-validation-summary="All" class="text-danger"></div> <!--This will display the error in a different text above all of the fields. List all the errors above the fields-->

        <div class="mb-3 row p-1">
            <label asp-for="FirstName" class="p-0"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="LastName" class="p-0"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Age" class="p-0"></label>
            <input asp-for="Age" class="form-control" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            
            <div class="col-6 col-md-3 mt-2">
                <a asp-controller="FakePerson" asp-action="Data" class="btn btn-outline-secondary border form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>